// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: contract/contracts.proto

package contractsV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContractState int32

const (
	ContractState_CONTRACT_STATE_UNSPECIFIED ContractState = 0
	ContractState_CONTRACT_STATE_DRAFT       ContractState = 1
	ContractState_CONTRACT_STATE_ACTIVE      ContractState = 2
	ContractState_CONTRACT_STATE_SUSPENDED   ContractState = 3
	ContractState_CONTRACT_STATE_TERMINATED  ContractState = 4
)

// Enum value maps for ContractState.
var (
	ContractState_name = map[int32]string{
		0: "CONTRACT_STATE_UNSPECIFIED",
		1: "CONTRACT_STATE_DRAFT",
		2: "CONTRACT_STATE_ACTIVE",
		3: "CONTRACT_STATE_SUSPENDED",
		4: "CONTRACT_STATE_TERMINATED",
	}
	ContractState_value = map[string]int32{
		"CONTRACT_STATE_UNSPECIFIED": 0,
		"CONTRACT_STATE_DRAFT":       1,
		"CONTRACT_STATE_ACTIVE":      2,
		"CONTRACT_STATE_SUSPENDED":   3,
		"CONTRACT_STATE_TERMINATED":  4,
	}
)

func (x ContractState) Enum() *ContractState {
	p := new(ContractState)
	*p = x
	return p
}

func (x ContractState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContractState) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_contracts_proto_enumTypes[0].Descriptor()
}

func (ContractState) Type() protoreflect.EnumType {
	return &file_contract_contracts_proto_enumTypes[0]
}

func (x ContractState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContractState.Descriptor instead.
func (ContractState) EnumDescriptor() ([]byte, []int) {
	return file_contract_contracts_proto_rawDescGZIP(), []int{0}
}

type OperationStatus int32

const (
	OperationStatus_OPERATION_STATUS_UNSPECIFIED OperationStatus = 0
	OperationStatus_OPERATION_STATUS_SUCCESS     OperationStatus = 1
	OperationStatus_OPERATION_STATUS_CREATED     OperationStatus = 2
	OperationStatus_OPERATION_STATUS_BAD_REQUEST OperationStatus = 3
	OperationStatus_OPERATION_STATUS_NOT_FOUND   OperationStatus = 4
	OperationStatus_OPERATION_STATUS_CONFLICT    OperationStatus = 5
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "OPERATION_STATUS_UNSPECIFIED",
		1: "OPERATION_STATUS_SUCCESS",
		2: "OPERATION_STATUS_CREATED",
		3: "OPERATION_STATUS_BAD_REQUEST",
		4: "OPERATION_STATUS_NOT_FOUND",
		5: "OPERATION_STATUS_CONFLICT",
	}
	OperationStatus_value = map[string]int32{
		"OPERATION_STATUS_UNSPECIFIED": 0,
		"OPERATION_STATUS_SUCCESS":     1,
		"OPERATION_STATUS_CREATED":     2,
		"OPERATION_STATUS_BAD_REQUEST": 3,
		"OPERATION_STATUS_NOT_FOUND":   4,
		"OPERATION_STATUS_CONFLICT":    5,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_contracts_proto_enumTypes[1].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_contract_contracts_proto_enumTypes[1]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_contract_contracts_proto_rawDescGZIP(), []int{1}
}

type CreateContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitiatorId   string                 `protobuf:"bytes,1,opt,name=initiator_id,json=initiatorId,proto3" json:"initiator_id,omitempty"`
	Details       *ContractDetails       `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContractRequest) Reset() {
	*x = CreateContractRequest{}
	mi := &file_contract_contracts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContractRequest) ProtoMessage() {}

func (x *CreateContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contracts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContractRequest.ProtoReflect.Descriptor instead.
func (*CreateContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_contracts_proto_rawDescGZIP(), []int{0}
}

func (x *CreateContractRequest) GetInitiatorId() string {
	if x != nil {
		return x.InitiatorId
	}
	return ""
}

func (x *CreateContractRequest) GetDetails() *ContractDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type UpdateContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdaterId     string                 `protobuf:"bytes,1,opt,name=updater_id,json=updaterId,proto3" json:"updater_id,omitempty"`
	ContractId    string                 `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Details       *ContractUpdate        `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContractRequest) Reset() {
	*x = UpdateContractRequest{}
	mi := &file_contract_contracts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContractRequest) ProtoMessage() {}

func (x *UpdateContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contracts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContractRequest.ProtoReflect.Descriptor instead.
func (*UpdateContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_contracts_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateContractRequest) GetUpdaterId() string {
	if x != nil {
		return x.UpdaterId
	}
	return ""
}

func (x *UpdateContractRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *UpdateContractRequest) GetDetails() *ContractUpdate {
	if x != nil {
		return x.Details
	}
	return nil
}

type GetContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractRequest) Reset() {
	*x = GetContractRequest{}
	mi := &file_contract_contracts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractRequest) ProtoMessage() {}

func (x *GetContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contracts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractRequest.ProtoReflect.Descriptor instead.
func (*GetContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_contracts_proto_rawDescGZIP(), []int{2}
}

func (x *GetContractRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

type ContractOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OperationStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=contracts.v1.OperationStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Contract      *Contract              `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractOperationResponse) Reset() {
	*x = ContractOperationResponse{}
	mi := &file_contract_contracts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractOperationResponse) ProtoMessage() {}

func (x *ContractOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contracts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractOperationResponse.ProtoReflect.Descriptor instead.
func (*ContractOperationResponse) Descriptor() ([]byte, []int) {
	return file_contract_contracts_proto_rawDescGZIP(), []int{3}
}

func (x *ContractOperationResponse) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *ContractOperationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ContractOperationResponse) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

type GetContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OperationStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=contracts.v1.OperationStatus" json:"status,omitempty"`
	Contract      *Contract              `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractResponse) Reset() {
	*x = GetContractResponse{}
	mi := &file_contract_contracts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractResponse) ProtoMessage() {}

func (x *GetContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contracts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractResponse.ProtoReflect.Descriptor instead.
func (*GetContractResponse) Descriptor() ([]byte, []int) {
	return file_contract_contracts_proto_rawDescGZIP(), []int{4}
}

func (x *GetContractResponse) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *GetContractResponse) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

type ContractDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyName   string                 `protobuf:"bytes,1,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	ContactEmail  string                 `protobuf:"bytes,2,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	MonthlyLimit  float32                `protobuf:"fixed32,3,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractDetails) Reset() {
	*x = ContractDetails{}
	mi := &file_contract_contracts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractDetails) ProtoMessage() {}

func (x *ContractDetails) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contracts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractDetails.ProtoReflect.Descriptor instead.
func (*ContractDetails) Descriptor() ([]byte, []int) {
	return file_contract_contracts_proto_rawDescGZIP(), []int{5}
}

func (x *ContractDetails) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *ContractDetails) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *ContractDetails) GetMonthlyLimit() float32 {
	if x != nil {
		return x.MonthlyLimit
	}
	return 0
}

func (x *ContractDetails) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ContractDetails) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type ContractUpdate struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	CompanyName   *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	ContactEmail  *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	MonthlyLimit  *wrapperspb.FloatValue  `protobuf:"bytes,3,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	EndDate       *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractUpdate) Reset() {
	*x = ContractUpdate{}
	mi := &file_contract_contracts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractUpdate) ProtoMessage() {}

func (x *ContractUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contracts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractUpdate.ProtoReflect.Descriptor instead.
func (*ContractUpdate) Descriptor() ([]byte, []int) {
	return file_contract_contracts_proto_rawDescGZIP(), []int{6}
}

func (x *ContractUpdate) GetCompanyName() *wrapperspb.StringValue {
	if x != nil {
		return x.CompanyName
	}
	return nil
}

func (x *ContractUpdate) GetContactEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.ContactEmail
	}
	return nil
}

func (x *ContractUpdate) GetMonthlyLimit() *wrapperspb.FloatValue {
	if x != nil {
		return x.MonthlyLimit
	}
	return nil
}

func (x *ContractUpdate) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type Contract struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyName    string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	ContactEmail   string                 `protobuf:"bytes,3,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	MonthlyLimit   float32                `protobuf:"fixed32,4,opt,name=monthly_limit,json=monthlyLimit,proto3" json:"monthly_limit,omitempty"`
	CurrentBalance float32                `protobuf:"fixed32,5,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	State          ContractState          `protobuf:"varint,6,opt,name=state,proto3,enum=contracts.v1.ContractState" json:"state,omitempty"`
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Contract) Reset() {
	*x = Contract{}
	mi := &file_contract_contracts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contract) ProtoMessage() {}

func (x *Contract) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contracts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contract.ProtoReflect.Descriptor instead.
func (*Contract) Descriptor() ([]byte, []int) {
	return file_contract_contracts_proto_rawDescGZIP(), []int{7}
}

func (x *Contract) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contract) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *Contract) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *Contract) GetMonthlyLimit() float32 {
	if x != nil {
		return x.MonthlyLimit
	}
	return 0
}

func (x *Contract) GetCurrentBalance() float32 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

func (x *Contract) GetState() ContractState {
	if x != nil {
		return x.State
	}
	return ContractState_CONTRACT_STATE_UNSPECIFIED
}

func (x *Contract) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Contract) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Contract) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Contract) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_contract_contracts_proto protoreflect.FileDescriptor

const file_contract_contracts_proto_rawDesc = "" +
	"\n" +
	"\x18contract/contracts.proto\x12\fcontracts.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"s\n" +
	"\x15CreateContractRequest\x12!\n" +
	"\finitiator_id\x18\x01 \x01(\tR\vinitiatorId\x127\n" +
	"\adetails\x18\x02 \x01(\v2\x1d.contracts.v1.ContractDetailsR\adetails\"\x8f\x01\n" +
	"\x15UpdateContractRequest\x12\x1d\n" +
	"\n" +
	"updater_id\x18\x01 \x01(\tR\tupdaterId\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x126\n" +
	"\adetails\x18\x03 \x01(\v2\x1c.contracts.v1.ContractUpdateR\adetails\"5\n" +
	"\x12GetContractRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\"\xa0\x01\n" +
	"\x19ContractOperationResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.contracts.v1.OperationStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\bcontract\x18\x03 \x01(\v2\x16.contracts.v1.ContractR\bcontract\"\x80\x01\n" +
	"\x13GetContractResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.contracts.v1.OperationStatusR\x06status\x122\n" +
	"\bcontract\x18\x02 \x01(\v2\x16.contracts.v1.ContractR\bcontract\"\xf0\x01\n" +
	"\x0fContractDetails\x12!\n" +
	"\fcompany_name\x18\x01 \x01(\tR\vcompanyName\x12#\n" +
	"\rcontact_email\x18\x02 \x01(\tR\fcontactEmail\x12#\n" +
	"\rmonthly_limit\x18\x03 \x01(\x02R\fmonthlyLimit\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\x8d\x02\n" +
	"\x0eContractUpdate\x12?\n" +
	"\fcompany_name\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\vcompanyName\x12A\n" +
	"\rcontact_email\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\fcontactEmail\x12@\n" +
	"\rmonthly_limit\x18\x03 \x01(\v2\x1b.google.protobuf.FloatValueR\fmonthlyLimit\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xcb\x03\n" +
	"\bContract\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcompany_name\x18\x02 \x01(\tR\vcompanyName\x12#\n" +
	"\rcontact_email\x18\x03 \x01(\tR\fcontactEmail\x12#\n" +
	"\rmonthly_limit\x18\x04 \x01(\x02R\fmonthlyLimit\x12'\n" +
	"\x0fcurrent_balance\x18\x05 \x01(\x02R\x0ecurrentBalance\x121\n" +
	"\x05state\x18\x06 \x01(\x0e2\x1b.contracts.v1.ContractStateR\x05state\x129\n" +
	"\n" +
	"start_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\xa1\x01\n" +
	"\rContractState\x12\x1e\n" +
	"\x1aCONTRACT_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CONTRACT_STATE_DRAFT\x10\x01\x12\x19\n" +
	"\x15CONTRACT_STATE_ACTIVE\x10\x02\x12\x1c\n" +
	"\x18CONTRACT_STATE_SUSPENDED\x10\x03\x12\x1d\n" +
	"\x19CONTRACT_STATE_TERMINATED\x10\x04*\xd0\x01\n" +
	"\x0fOperationStatus\x12 \n" +
	"\x1cOPERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18OPERATION_STATUS_SUCCESS\x10\x01\x12\x1c\n" +
	"\x18OPERATION_STATUS_CREATED\x10\x02\x12 \n" +
	"\x1cOPERATION_STATUS_BAD_REQUEST\x10\x03\x12\x1e\n" +
	"\x1aOPERATION_STATUS_NOT_FOUND\x10\x04\x12\x1d\n" +
	"\x19OPERATION_STATUS_CONFLICT\x10\x052\xa6\x02\n" +
	"\x10ContractsService\x12^\n" +
	"\x0eCreateContract\x12#.contracts.v1.CreateContractRequest\x1a'.contracts.v1.ContractOperationResponse\x12^\n" +
	"\x0eUpdateContract\x12#.contracts.v1.UpdateContractRequest\x1a'.contracts.v1.ContractOperationResponse\x12R\n" +
	"\vGetContract\x12 .contracts.v1.GetContractRequest\x1a!.contracts.v1.GetContractResponseBJZHgithub.com/Nikita213-hub/travel_proto_contracts/pkg/proto/v1;contractsV1b\x06proto3"

var (
	file_contract_contracts_proto_rawDescOnce sync.Once
	file_contract_contracts_proto_rawDescData []byte
)

func file_contract_contracts_proto_rawDescGZIP() []byte {
	file_contract_contracts_proto_rawDescOnce.Do(func() {
		file_contract_contracts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_contracts_proto_rawDesc), len(file_contract_contracts_proto_rawDesc)))
	})
	return file_contract_contracts_proto_rawDescData
}

var file_contract_contracts_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_contract_contracts_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_contract_contracts_proto_goTypes = []any{
	(ContractState)(0),                // 0: contracts.v1.ContractState
	(OperationStatus)(0),              // 1: contracts.v1.OperationStatus
	(*CreateContractRequest)(nil),     // 2: contracts.v1.CreateContractRequest
	(*UpdateContractRequest)(nil),     // 3: contracts.v1.UpdateContractRequest
	(*GetContractRequest)(nil),        // 4: contracts.v1.GetContractRequest
	(*ContractOperationResponse)(nil), // 5: contracts.v1.ContractOperationResponse
	(*GetContractResponse)(nil),       // 6: contracts.v1.GetContractResponse
	(*ContractDetails)(nil),           // 7: contracts.v1.ContractDetails
	(*ContractUpdate)(nil),            // 8: contracts.v1.ContractUpdate
	(*Contract)(nil),                  // 9: contracts.v1.Contract
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil),    // 11: google.protobuf.StringValue
	(*wrapperspb.FloatValue)(nil),     // 12: google.protobuf.FloatValue
}
var file_contract_contracts_proto_depIdxs = []int32{
	7,  // 0: contracts.v1.CreateContractRequest.details:type_name -> contracts.v1.ContractDetails
	8,  // 1: contracts.v1.UpdateContractRequest.details:type_name -> contracts.v1.ContractUpdate
	1,  // 2: contracts.v1.ContractOperationResponse.status:type_name -> contracts.v1.OperationStatus
	9,  // 3: contracts.v1.ContractOperationResponse.contract:type_name -> contracts.v1.Contract
	1,  // 4: contracts.v1.GetContractResponse.status:type_name -> contracts.v1.OperationStatus
	9,  // 5: contracts.v1.GetContractResponse.contract:type_name -> contracts.v1.Contract
	10, // 6: contracts.v1.ContractDetails.start_date:type_name -> google.protobuf.Timestamp
	10, // 7: contracts.v1.ContractDetails.end_date:type_name -> google.protobuf.Timestamp
	11, // 8: contracts.v1.ContractUpdate.company_name:type_name -> google.protobuf.StringValue
	11, // 9: contracts.v1.ContractUpdate.contact_email:type_name -> google.protobuf.StringValue
	12, // 10: contracts.v1.ContractUpdate.monthly_limit:type_name -> google.protobuf.FloatValue
	10, // 11: contracts.v1.ContractUpdate.end_date:type_name -> google.protobuf.Timestamp
	0,  // 12: contracts.v1.Contract.state:type_name -> contracts.v1.ContractState
	10, // 13: contracts.v1.Contract.start_date:type_name -> google.protobuf.Timestamp
	10, // 14: contracts.v1.Contract.end_date:type_name -> google.protobuf.Timestamp
	10, // 15: contracts.v1.Contract.created_at:type_name -> google.protobuf.Timestamp
	10, // 16: contracts.v1.Contract.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 17: contracts.v1.ContractsService.CreateContract:input_type -> contracts.v1.CreateContractRequest
	3,  // 18: contracts.v1.ContractsService.UpdateContract:input_type -> contracts.v1.UpdateContractRequest
	4,  // 19: contracts.v1.ContractsService.GetContract:input_type -> contracts.v1.GetContractRequest
	5,  // 20: contracts.v1.ContractsService.CreateContract:output_type -> contracts.v1.ContractOperationResponse
	5,  // 21: contracts.v1.ContractsService.UpdateContract:output_type -> contracts.v1.ContractOperationResponse
	6,  // 22: contracts.v1.ContractsService.GetContract:output_type -> contracts.v1.GetContractResponse
	20, // [20:23] is the sub-list for method output_type
	17, // [17:20] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_contract_contracts_proto_init() }
func file_contract_contracts_proto_init() {
	if File_contract_contracts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_contracts_proto_rawDesc), len(file_contract_contracts_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_contracts_proto_goTypes,
		DependencyIndexes: file_contract_contracts_proto_depIdxs,
		EnumInfos:         file_contract_contracts_proto_enumTypes,
		MessageInfos:      file_contract_contracts_proto_msgTypes,
	}.Build()
	File_contract_contracts_proto = out.File
	file_contract_contracts_proto_goTypes = nil
	file_contract_contracts_proto_depIdxs = nil
}
